apiVersion: apps/v1
kind: Deployment
metadata:
  name: demowebapp
  labels:
    app: demowebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demowebapp
  template:
    metadata:
      name: demowebapp
      labels:
        app: demowebapp
    spec:
      containers:
        - name: demowebapp
          image: quay.io/shubhayu_chongder/springboot-demo:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080

          volumeMounts:
          - name: application-config
            mountPath: "/config"
            readOnly: true
      volumes:
      - name: application-config
        configMap:
          name: spring-app-config
          items:
          - key: application.properties
            path: application.properties
